export default {		
	redisactive: redisport => `Redis na porta ${redisport}`,
	rediserror: redisport => `Impossível conectar ao Redis na porta ${redisport}.`,
	commanderror: () => `Problema ao executar o comando.`,
	playing: videotitle => `Tocando \`${videotitle}\`!`,
	addedtoqueue: () => `Adicionado a fila!`,
	queueadderror: () => `Erro ao adicionar, conteúdo com restrição ou cota de busca no youtube estourada (tente tocar com o link)`,
	queuetitle: () => `Fila`,
	queuedesc: (page, pages) => `Página ${page} / ${pages}`,
	itemtitle: (index, title, author) => `${index}) "${title}" por ${author}`, 	
	itemdesc: (views) => `\`${views}\` visualizações`,	
	unknowntitle: () => `Indisponível`,
	unkownauthor: () => `Autor desconhecido`,
	processing: () => `Aguarde...`,
	emptyqueue: () => `Fila vazia.`,	
	skipped: () => `Pulou!`,	
	helptitle: () => `Ajuda`,
	helpdesc: () => `Comandos:`,	
	help: prefix => `Ajuda dos comandos, ver outra página com \`${prefix}ajuda <pagina>\`.`,
	play: prefix => `Toca uma música com \`${prefix}toca <URL|termo>\`. Se já tiver música tocando use o \`${prefix}bota <url|termo>\``,		
	queue: () => `Mostra a fila.`,	
	skip: () => `Pula a música.`,	
	stop: () => `Para tudo, limpa fila e sai do canal.`,	
};
